### ISSUE TITLE
Test results in a "expected abc / got abc" form

### ISSUE THREAD

**Issue by pcotret** [riscv-software-src/riscv-tests#345]
I would like to get my test results with a short message like:
"expected 5 / got 6" as, for the moment, I only get an "ERROR" at the end of tests for my instruction.

Is there a way to do that? It would help me to identify the test being wrong and what is the result of the instruction..

**Comment by MikeDoingThings** [comment]
Hi, 
As far as I know there is a section in the linker script (see /env/p/link.ld within this repository) that is called ".tohost". As long as the text.init section is not too big (which it probably will not be), the exact address should be 0x80001000. This is the address where at the end of the test program's execution, the information about passing or failing is stored to. If your implementation passes the test, it will write 0x1 to the .tohost address, otherwise it will send some odd number. The odd number is basically the testnumber shifted left by one bit and then having the least significant bit set to 1. So in other words: 

(Value at 0x80001000 >> 1)  <=> number of the failed test within the program

Hope this helps. 

Mike
