### ISSUE TITLE
Does the IcountTest need to be improved?

### ISSUE THREAD

**Issue by lz-bro** [riscv-software-src/riscv-tests#516]
https://github.com/riscv-software-src/riscv-tests/blob/c36c814ae49610bc407a5c4e144866fa50e4510e/debug/gdbserver.py#L2059-L2083

In this test, count are set to 1 and 2 respectively. But, it is mentioned in RISC-V External Debug Support Version 0.13.2 that count may only support 1.
<img width="602" alt="icount" src="https://github.com/riscv-software-src/riscv-tests/assets/111737414/728f8660-4c17-4f0a-aeb6-7b714b196826">
If the hardware only supports count 1, but if count was set to 2, the hardware will process count to 1, causing set_trigger fail due to inconsistent writing and reading back of tdata1.

**Comment by timsifive** [comment]
Most of these tests are written to run well against spike, and unfortunately not against more general hardware. I think it's great that you're going through and noting some of these issues.

What should happen on hardware that supports count=1 but not count=2 is that `riscv icount set m 2` returns an error.  OpenOCD will read back tdata1 after writing it, and should return an error because the hardware doesn't let count=2 be written.

From the test framework, this means that we need a hart property: max_icount or something. Then in the test we can confirm that either icount works, or we get an error when setting it.

**Comment by lz-bro** [comment]
Thank you very much for your reply and suggestions.
